### ISSUE TITLE
remove media-query related stuffs

### ISSUE THREAD

**Issue by VinSpee** [ScalesCSS/scales#9]
I think it's more of a detriment than a benefit. Maybe we make them into separate patterns?

**Comment by yodasw16** [comment]
This was done in the v2 rewrite https://github.com/ScalesCSS/scales/commit/c0dccbfa0eef364f7d76ab6a80f29e4766c4cb62. There are a couple of media queries for patterns where the default pattern is the large screen view, but I give the option to set a breakpoint for when to change the pattern for a smaller viewport. For example: https://github.com/ScalesCSS/patterns-flag/blob/master/_flag.scss#L180-L251
